In [1]:
import pandas as pd
import gc
gc.collect()

0

In [2]:
train = pd.read_csv("tmp.csv")

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495242 entries, 0 to 495241
Columns: 101 entries, Unnamed: 0 to work_long
dtypes: float64(78), int64(9), object(14)
memory usage: 381.6+ MB

In [4]:
train.head()

,Unnamed: 0,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,home_ownership,...,disbursement_method,debt_settlement_flag,last_credit_pull_d_month,last_credit_pull_d_year,loan_month,loan_year,loan_last_start,label,long_year,work_long
0,0,30000.0,30000.0,30000.0,36 months,7.34,930.99,A,A4,OWN,...,Cash,N,1,2019,3,2018,10,0,10,3
1,1,34825.0,34825.0,34825.0,60 months,12.61,785.45,C,C1,MORTGAGE,...,Cash,N,2,2019,3,2018,11,0,16,2
2,2,2600.0,2600.0,2600.0,36 months,7.96,81.43,A,A5,MORTGAGE,...,Cash,N,2,2019,3,2018,11,0,8,3
3,3,20000.0,20000.0,20000.0,60 months,9.92,424.16,B,B2,MORTGAGE,...,Cash,N,2,2019,3,2018,11,0,18,3
4,4,17000.0,17000.0,17000.0,60 months,20.39,454.10,D,D4,RENT,...,Cash,N,2,2019,3,2018,11,0,20,10

In [5]:
train.drop(["Unnamed: 0"],axis=1,inplace=True)

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495242 entries, 0 to 495241
Data columns (total 100 columns):
loan_amnt                     495242 non-null float64
funded_amnt                   495242 non-null float64
funded_amnt_inv               495242 non-null float64
term                          495242 non-null object
int_rate                      495242 non-null float64
installment                   495242 non-null float64
grade                         495242 non-null object
sub_grade                     495242 non-null object
home_ownership                495242 non-null object
annual_inc                    495242 non-null float64
verification_status           495242 non-null object
pymnt_plan                    495242 non-null object
purpose                       495242 non-null object
title                         495242 non-null object
addr_state                    495242 non-null object
dti                           494110 non-null float64
delinq_2yrs                   495242 non-null float64
inq_last_6mths                495242 non-null float64
open_acc                      495242 non-null float64
pub_rec                       495242 non-null float64
revol_bal                     495242 non-null float64
total_acc                     495242 non-null float64
initial_list_status           495242 non-null object
out_prncp                     495242 non-null float64
out_prncp_inv                 495242 non-null float64
total_pymnt                   495242 non-null float64
total_pymnt_inv               495242 non-null float64
total_rec_prncp               495242 non-null float64
total_rec_int                 495242 non-null float64
total_rec_late_fee            495242 non-null float64
recoveries                    495242 non-null float64
collection_recovery_fee       495242 non-null float64
last_pymnt_amnt               495242 non-null float64
collections_12_mths_ex_med    495242 non-null float64
policy_code                   495242 non-null float64
application_type              495242 non-null object
acc_now_delinq                495242 non-null float64
tot_coll_amt                  495242 non-null float64
tot_cur_bal                   495242 non-null float64
open_acc_6m                   495242 non-null float64
open_act_il                   495242 non-null float64
open_il_12m                   495242 non-null float64
open_il_24m                   495242 non-null float64
mths_since_rcnt_il            476832 non-null float64
total_bal_il                  495242 non-null float64
il_util                       414418 non-null float64
open_rv_12m                   495242 non-null float64
open_rv_24m                   495242 non-null float64
max_bal_bc                    495242 non-null float64
all_util                      495113 non-null float64
total_rev_hi_lim              495242 non-null float64
inq_fi                        495242 non-null float64
total_cu_tl                   495242 non-null float64
inq_last_12m                  495242 non-null float64
acc_open_past_24mths          495242 non-null float64
avg_cur_bal                   495202 non-null float64
bc_open_to_buy                488654 non-null float64
bc_util                       488439 non-null float64
chargeoff_within_12_mths      495242 non-null float64
delinq_amnt                   495242 non-null float64
mo_sin_old_il_acct            476832 non-null float64
mo_sin_old_rev_tl_op          495242 non-null float64
mo_sin_rcnt_rev_tl_op         495242 non-null float64
mo_sin_rcnt_tl                495242 non-null float64
mort_acc                      495242 non-null float64
mths_since_recent_bc          489044 non-null float64
mths_since_recent_inq         433937 non-null float64
num_accts_ever_120_pd         495242 non-null float64
num_actv_bc_tl                495242 non-null float64
num_actv_rev_tl               495242 non-null float64
num_bc_sats                   495242 non-null float64
num_bc_tl                     495242 non-null float64
num_il_tl                     495242 non-null float64
num_op_rev_tl                 495242 non-null float64
num_rev_accts                 495242 non-null float64
num_rev_tl_bal_gt_0           495242 non-null float64
num_sats                      495242 non-null float64
num_tl_120dpd_2m              482838 non-null float64
num_tl_30dpd                  495242 non-null float64
num_tl_90g_dpd_24m            495242 non-null float64
num_tl_op_past_12m            495242 non-null float64
pct_tl_nvr_dlq                495240 non-null float64
percent_bc_gt_75              488646 non-null float64
pub_rec_bankruptcies          495242 non-null float64
tax_liens                     495242 non-null float64
tot_hi_cred_lim               495242 non-null float64
total_bal_ex_mort             495242 non-null float64
total_bc_limit                495242 non-null float64
total_il_high_credit_limit    495242 non-null float64
hardship_flag                 495242 non-null object
disbursement_method           495242 non-null object
debt_settlement_flag          495242 non-null object
last_credit_pull_d_month      495242 non-null int64
last_credit_pull_d_year       495242 non-null int64
loan_month                    495242 non-null int64
loan_year                     495242 non-null int64
loan_last_start               495242 non-null int64
label                         495242 non-null int64
long_year                     495242 non-null int64
work_long                     495242 non-null int64
dtypes: float64(78), int64(8), object(14)
memory usage: 377.8+ MB

In [13]:
train.isnull().sum()

loan_amnt                     0
funded_amnt                   0
funded_amnt_inv               0
term                          0
int_rate                      0
installment                   0
grade                         0
sub_grade                     0
home_ownership                0
annual_inc                    0
verification_status           0
pymnt_plan                    0
purpose                       0
title                         0
addr_state                    0
dti                           0
delinq_2yrs                   0
inq_last_6mths                0
open_acc                      0
pub_rec                       0
revol_bal                     0
total_acc                     0
initial_list_status           0
out_prncp                     0
out_prncp_inv                 0
total_pymnt                   0
total_pymnt_inv               0
total_rec_prncp               0
total_rec_int                 0
total_rec_late_fee            0
                             ..
num_actv_rev_tl               0
num_bc_sats                   0
num_bc_tl                     0
num_il_tl                     0
num_op_rev_tl                 0
num_rev_accts                 0
num_rev_tl_bal_gt_0           0
num_sats                      0
num_tl_120dpd_2m              0
num_tl_30dpd                  0
num_tl_90g_dpd_24m            0
num_tl_op_past_12m            0
pct_tl_nvr_dlq                2
pub_rec_bankruptcies          0
tax_liens                     0
tot_hi_cred_lim               0
total_bal_ex_mort             0
total_bc_limit                0
total_il_high_credit_limit    0
hardship_flag                 0
disbursement_method           0
debt_settlement_flag          0
last_credit_pull_d_month      0
last_credit_pull_d_year       0
loan_month                    0
loan_year                     0
loan_last_start               0
label                         0
long_year                     0
work_long                     0
Length: 99, dtype: int64

In [8]:
train.dti = train.dti.fillna(train.dti.mean())

In [9]:
train.num_tl_120dpd_2m = train.num_tl_120dpd_2m.fillna(0)

In [12]:
train.drop(["percent_bc_gt_75"],axis=1,inplace=True)

In [15]:
for i in train.isnull().sum().keys():
    if train.isnull().sum()[i] != 0:
        print(i)

mths_since_rcnt_il
il_util
all_util
avg_cur_bal
bc_open_to_buy
bc_util
mo_sin_old_il_acct
mths_since_recent_bc
mths_since_recent_inq
pct_tl_nvr_dlq

In [17]:
train.mths_since_rcnt_il = train.mths_since_rcnt_il.fillna(train.mths_since_rcnt_il.mean())

In [21]:
train.il_util = train.il_util.fillna(train.il_util.mean())

In [24]:
train.all_util = train.all_util.fillna(train.all_util.mean())

In [26]:
train.avg_cur_bal = train.avg_cur_bal.fillna(train.avg_cur_bal.mean())

In [29]:
train.bc_open_to_buy = train.bc_open_to_buy.fillna(train.bc_open_to_buy.mean())

In [31]:
train.bc_util = train.bc_util.fillna(train.bc_util.mean())

In [33]:
train.mo_sin_old_il_acct = train.mo_sin_old_il_acct.fillna(train.mo_sin_old_il_acct.mean())

In [35]:
train.mths_since_recent_bc =train.mths_since_recent_bc.fillna(train.mths_since_recent_bc.mean())

In [37]:
train.mths_since_recent_inq = train.mths_since_recent_inq.fillna(train.mths_since_recent_inq.mean())

In [38]:
train.pct_tl_nvr_dlq = train.pct_tl_nvr_dlq.fillna(train.pct_tl_nvr_dlq.mean())

In [39]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495242 entries, 0 to 495241
Data columns (total 99 columns):
loan_amnt                     495242 non-null float64
funded_amnt                   495242 non-null float64
funded_amnt_inv               495242 non-null float64
term                          495242 non-null object
int_rate                      495242 non-null float64
installment                   495242 non-null float64
grade                         495242 non-null object
sub_grade                     495242 non-null object
home_ownership                495242 non-null object
annual_inc                    495242 non-null float64
verification_status           495242 non-null object
pymnt_plan                    495242 non-null object
purpose                       495242 non-null object
title                         495242 non-null object
addr_state                    495242 non-null object
dti                           495242 non-null float64
delinq_2yrs                   495242 non-null float64
inq_last_6mths                495242 non-null float64
open_acc                      495242 non-null float64
pub_rec                       495242 non-null float64
revol_bal                     495242 non-null float64
total_acc                     495242 non-null float64
initial_list_status           495242 non-null object
out_prncp                     495242 non-null float64
out_prncp_inv                 495242 non-null float64
total_pymnt                   495242 non-null float64
total_pymnt_inv               495242 non-null float64
total_rec_prncp               495242 non-null float64
total_rec_int                 495242 non-null float64
total_rec_late_fee            495242 non-null float64
recoveries                    495242 non-null float64
collection_recovery_fee       495242 non-null float64
last_pymnt_amnt               495242 non-null float64
collections_12_mths_ex_med    495242 non-null float64
policy_code                   495242 non-null float64
application_type              495242 non-null object
acc_now_delinq                495242 non-null float64
tot_coll_amt                  495242 non-null float64
tot_cur_bal                   495242 non-null float64
open_acc_6m                   495242 non-null float64
open_act_il                   495242 non-null float64
open_il_12m                   495242 non-null float64
open_il_24m                   495242 non-null float64
mths_since_rcnt_il            495242 non-null float64
total_bal_il                  495242 non-null float64
il_util                       495242 non-null float64
open_rv_12m                   495242 non-null float64
open_rv_24m                   495242 non-null float64
max_bal_bc                    495242 non-null float64
all_util                      495242 non-null float64
total_rev_hi_lim              495242 non-null float64
inq_fi                        495242 non-null float64
total_cu_tl                   495242 non-null float64
inq_last_12m                  495242 non-null float64
acc_open_past_24mths          495242 non-null float64
avg_cur_bal                   495242 non-null float64
bc_open_to_buy                495242 non-null float64
bc_util                       495242 non-null float64
chargeoff_within_12_mths      495242 non-null float64
delinq_amnt                   495242 non-null float64
mo_sin_old_il_acct            495242 non-null float64
mo_sin_old_rev_tl_op          495242 non-null float64
mo_sin_rcnt_rev_tl_op         495242 non-null float64
mo_sin_rcnt_tl                495242 non-null float64
mort_acc                      495242 non-null float64
mths_since_recent_bc          495242 non-null float64
mths_since_recent_inq         495242 non-null float64
num_accts_ever_120_pd         495242 non-null float64
num_actv_bc_tl                495242 non-null float64
num_actv_rev_tl               495242 non-null float64
num_bc_sats                   495242 non-null float64
num_bc_tl                     495242 non-null float64
num_il_tl                     495242 non-null float64
num_op_rev_tl                 495242 non-null float64
num_rev_accts                 495242 non-null float64
num_rev_tl_bal_gt_0           495242 non-null float64
num_sats                      495242 non-null float64
num_tl_120dpd_2m              495242 non-null float64
num_tl_30dpd                  495242 non-null float64
num_tl_90g_dpd_24m            495242 non-null float64
num_tl_op_past_12m            495242 non-null float64
pct_tl_nvr_dlq                495242 non-null float64
pub_rec_bankruptcies          495242 non-null float64
tax_liens                     495242 non-null float64
tot_hi_cred_lim               495242 non-null float64
total_bal_ex_mort             495242 non-null float64
total_bc_limit                495242 non-null float64
total_il_high_credit_limit    495242 non-null float64
hardship_flag                 495242 non-null object
disbursement_method           495242 non-null object
debt_settlement_flag          495242 non-null object
last_credit_pull_d_month      495242 non-null int64
last_credit_pull_d_year       495242 non-null int64
loan_month                    495242 non-null int64
loan_year                     495242 non-null int64
loan_last_start               495242 non-null int64
label                         495242 non-null int64
long_year                     495242 non-null int64
work_long                     495242 non-null int64
dtypes: float64(77), int64(8), object(14)
memory usage: 374.1+ MB

In [41]:
train = pd.get_dummies(train)

In [42]:
train.head()

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,disbursement_method_Cash,disbursement_method_DirectPay,debt_settlement_flag_N,debt_settlement_flag_Y
0,30000.0,30000.0,30000.0,7.34,930.99,95000.0,16.18,1.0,0.0,10.0,...,0,1,1,0,1,0,1,0,1,0
1,34825.0,34825.0,34825.0,12.61,785.45,125000.0,21.31,0.0,0.0,12.0,...,0,1,1,0,1,0,1,0,1,0
2,2600.0,2600.0,2600.0,7.96,81.43,62000.0,19.61,0.0,0.0,8.0,...,0,1,1,0,1,0,1,0,1,0
3,20000.0,20000.0,20000.0,9.92,424.16,110000.0,10.56,0.0,0.0,9.0,...,0,1,1,0,1,0,1,0,1,0
4,17000.0,17000.0,17000.0,20.39,454.10,52000.0,15.65,0.0,0.0,9.0,...,0,1,1,0,1,0,1,0,1,0

In [43]:
for col in train.select_dtypes(include=['object']).columns:
    train.drop(col,axis=1,inplace=True)

In [44]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495242 entries, 0 to 495241
Columns: 223 entries, loan_amnt to debt_settlement_flag_Y
dtypes: float64(77), int64(8), uint8(138)
memory usage: 386.3 MB

In [45]:
y  = train.label

In [46]:
x = train.drop(["label"],axis=1,inplace=True)

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn import ensemble
from sklearn.preprocessing import OneHotEncoder

In [51]:
x = train

In [52]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2, random_state=123)

In [53]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(396193, 222)
(396193,)
(99049, 222)
(99049,)

In [55]:
import xgboost as xgb
from sklearn.ensemble import ExtraTreesRegressor, RandomForestRegressor

In [57]:
clf2 = xgb.XGBClassifier(n_estimators=500, max_depth=3, 
                            learning_rate=0.01, subsample=0.8, colsample_bytree=0.3,scale_pos_weight=3.0, 
                             silent=True, nthread=-1, seed=0, missing=None,objective='binary:logistic', 
                             reg_alpha=1, reg_lambda=1, 
                             gamma=0, min_child_weight=1, 
                             max_delta_step=0,base_score=0.5)

clf2.fit(x_train, y_train)
print (clf2.score(x_test, y_test))

0.9852598208967279